Some cleanups for posts and sidebar
olauncher/olauncher.github.io pull request #1
Opened 2024-03-19 06:07 UTC by DevBefell

Fixed some of the latest post's dates as well as managed the consistency of the titles.
Also updated Account Support link
For consistency I changed the version titles to (Minecraft VERSION: UPDATE NAME) and the posts to (DATE-release-VERSION).
It was the old way Minecraft did their post (now its "is out on Java") and is now much more distinct what posts are for what versions.

2024-03-19 16:15 UTC, bigfoot547 commented
Sorry, university is acting up. I will try and look it over later today or tomorrow. thanks

2024-03-22 08:26 UTC, bigfoot547 requested changes
borders

2024-03-22 08:26 UTC, bigfoot547 commented on _includes/sidebar.html
> -  <a href="https://github.com/olauncher"><img src="{{ site.baseurl }}/img/olauncher_logo_150.png" border="0"></a>
Your removal of `border="0"` causes borders to appear:
<details>
<summary>image</summary>
<img src="https://github.com/olauncher/olauncher.github.io/assets/21959175/e9df32b5-c281-4eeb-842b-cac20185f764" alt="OLauncher sidebar with borders" />
</details>

2024-03-22 20:41 UTC, DevBefell commented
Added it back.

2024-03-23 02:43 UTC, bigfoot547 approved these changes
looks good

2024-03-23 02:44 UTC, merged